LNAME = JUN
LNAME = KIM
FNAME = JUNHEE

LNAME += DOA

NAME = '"PACK KIM"'

A = ${B} AA
B = BB

a := ${b} aa

b := bb



all :
	@echo ${NAME}
#	@echo A= ${A}
#	@echo a= ${a}
#	@echo LNAME= ${LNAME}
#	@echo ${LNAME}, ${FNAME}
#	@echo macro_${LNAME}
#	@echo Mr. ${LNAME}
#	@echo Mr. ${LNAME}.Room101
	 
